### PR TITLE
Defining terms

### PR DESCRIPTION
**Pull request by sudo-bmitch**
This cleans up `Refers` to `refers` and documents the terms we are using in the Definitions section.

The only concern I have is changing `Artifact` to `Object` because we overloaded that term with the introduction of the `Artifact Manifest`. Is there a better word for a generic artifact that includes the Image and Artifact manifest plus their associated blobs?

Signed-off-by: Brandon Mitchell <git@bmitch.net>

### CODE REVIEW

**Comment by rchincha** [comment]
> Artifact: one conceptual piece of content stored as Blobs with an accompanying Manifest containing a Config

"image content"?

Also, perhaps add a note that this term was "previously known as ..."

**Comment by sudo-bmitch** [comment]
> "image content"?

I've been avoiding "image" in the term because it implies the Image Manifest, and we're now pushing content that isn't an image, like signatures and SBOMs.

> Also, perhaps add a note that this term was "previously known as ..."

Good call out, I'll update that when we get a better name.

**Review by jdolitsky — APPROVED** [review]
This LGTM

**Comment by sudo-bmitch** [comment]
This should be ready to merge to make it visible upstream. The latest change deleted the separate upgrading document and merged the content back into `spec.md` along with including other feedback from comments on the upstream PR.

**Pull request merged**
